"use client";
// import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Roboto_Slab } from "next/font/google";
import CartProvider from "@/app/_context/CardContext"
import {
  ClerkProvider,
 // SignInButton,
  SignedIn,
  //SignedOut,
  //UserButton,
} from "@clerk/nextjs";
const roboto = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <CartProvider>
      <html lang="en">
        <body className={` ${roboto.className}  bg-gray-50 `}>
          <Header />
          <SignedIn></SignedIn>
          {children}
          <Footer />
        </body>
      </html>
      </CartProvider>
    </ClerkProvider>
  );
}
